// import '../MedButton/src/index.less'
// import '../MedSTable/src/index.less'
// import '../MedSRadio/src/index.less'
// import '../MedSCheckbox/src/index.less'
// import '../MedSForm/src/index.less'
// import '../MedSCard/src/index.less'
// import '../MedSSticker/src/index.less'
import './index.less'
import './theme-antd-weak.css'
import './theme-antd-gray.css'
import './theme-antd-dark.css'
